// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCueFBUZ2fSdBl2f4UBTFouW3HhH6nkIfQ',
    appId: '1:689494712485:web:fca17246cd970229572d4c',
    messagingSenderId: '689494712485',
    projectId: 'foodfinds-2b78e',
    authDomain: 'foodfinds-2b78e.firebaseapp.com',
    databaseURL: 'https://foodfinds-2b78e-default-rtdb.firebaseio.com',
    storageBucket: 'foodfinds-2b78e.appspot.com',
    measurementId: 'G-5XPSG0CM58',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWqy3qOqI0gGfJPlzqx8wParcltooXCxo',
    appId: '1:689494712485:android:40987c88b44a40a7572d4c',
    messagingSenderId: '689494712485',
    projectId: 'foodfinds-2b78e',
    databaseURL: 'https://foodfinds-2b78e-default-rtdb.firebaseio.com',
    storageBucket: 'foodfinds-2b78e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjfkscm4Rfz0rO5TkjN5Oe0l4X9BSBK5M',
    appId: '1:689494712485:ios:282fd43b8fa15c93572d4c',
    messagingSenderId: '689494712485',
    projectId: 'foodfinds-2b78e',
    databaseURL: 'https://foodfinds-2b78e-default-rtdb.firebaseio.com',
    storageBucket: 'foodfinds-2b78e.appspot.com',
    iosBundleId: 'com.example.foodfinds',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjfkscm4Rfz0rO5TkjN5Oe0l4X9BSBK5M',
    appId: '1:689494712485:ios:282fd43b8fa15c93572d4c',
    messagingSenderId: '689494712485',
    projectId: 'foodfinds-2b78e',
    databaseURL: 'https://foodfinds-2b78e-default-rtdb.firebaseio.com',
    storageBucket: 'foodfinds-2b78e.appspot.com',
    iosBundleId: 'com.example.foodfinds',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCueFBUZ2fSdBl2f4UBTFouW3HhH6nkIfQ',
    appId: '1:689494712485:web:289eb616850905d8572d4c',
    messagingSenderId: '689494712485',
    projectId: 'foodfinds-2b78e',
    authDomain: 'foodfinds-2b78e.firebaseapp.com',
    databaseURL: 'https://foodfinds-2b78e-default-rtdb.firebaseio.com',
    storageBucket: 'foodfinds-2b78e.appspot.com',
    measurementId: 'G-Y6T4YT145K',
  );
}
